name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Copy source code to package folder
        run: |
          mkdir package
          # Copiar todos los archivos .py desde app/
          cp -r app/*.py package/
          # Copiar archivos de subcarpetas dentro de app/
          cp -r app/utils/*.py package/
          cp -r app/services/*.py package/

      - name: Create Zip file for Lambda function
        run: |
          cd package
          zip -r ../code.zip .

      - name: Deploy to AWS Lambda
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:us-east-2:816069150902:function:AgentAI-Reservas \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
